### ISSUE TITLE
New release planned?

### ISSUE THREAD

**Issue by oschrenk** [emartech/pure-scheduler#149]
It seems that 0.4.4 is not available (on Maven Central). At https://search.maven.org/artifact/com.emarsys/scheduler_2.13 I can only see 0.4.3.

Are any new releases planned?

**Comment by miklos-martin** [comment]
Hi, sorry, I've been neglecting this library lately. I plan to do some housekeeping and a new release next friday.
Scala3 and CE3 support is also coming, but at least another week later.

**Comment by miklos-martin** [comment]
Hi @oschrenk,

Sorry for the delay. Turns out that publishing 0.4.4 failed on travis, and I can no longer log in there for some reason. I've moved the CI to GitHub Actions, and published 0.4.5, which is identical to 0.4.4 regarding the code. Soon it will be available on maven central.

I'm closing this now, but will update dependencies and publish for cats 2.x again soon ™️ .
